# -*- coding: utf-8 -*-
"""felici_rand.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11dKVP74feAJ-sHct6EKUaMC-ZJFnSZKR
"""

def felicidades(*args):
  import random
  var=args[0]  
  opts=args[0]
  feli1 = random.choice(['¡Felicidades!', ' ', 'En buena hora' , 'Que admirable' , 'Que suerte', 'Que envidia' , '¿Enserio?'])
  
  feli2 = random.choice(['Espero que de aquí en adelante todo siga saliendo bien',  'Espero que todo salga bien', 'Solo era cuestión de tiempo' , 'Sabía que lo conseguirías', 'Sabía que lo lograrías' , 'Sabía que podías hacerlo', 'Sabía que erez capaz de hacerlo', 'Sabía que eres capaz de lograrlo', 'Sabía que eres capaz de hacerlo' , 'Ya me contarás después que pasa', 'Hay que celebrarlo', 'Hay que hacer algo especial', 'Valio la pena tu esfuerza'])
  
  feli3 = random.choice(['Me alegra', 'Me da felicidad', 'Me alegro mucho' , 'Me da mucha alegría', 'Me da mucha felicidad', 'Me da placer escuchar sobre', 'Me es fantastico escuchar sobre', 'Me es estupendo escuchar sobre', 'Me es maravilloso', 'Me es maravilloso', 'Me es geníal', 'Que genial', 'Es genial'])
 
  feli4 = random.choice(['Que gusto', 'Que Alegría', 'Que placer' , 'Que gozo' , 'Que deleite', 'Que felicidad']+[opts])

  fele = random.choice([(feli1, 'podrías recompensarte con algo que te guste'), (feli1, feli2 , 'auto recompensarte es bueno para que te sientas mejor por tu logro'), (feli1, feli2, feli3, "tu logro" ),(feli1, feli2, feli4, "me da escuchar sobre tu logro " ,'Seria divertido celebrarlo con algo')])

  return 'set_slot {0} "{1}"'.format(var,fele)