# -*- coding: utf-8 -*-
"""Pre_random.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oDHGx57TL4Ok_Fl9BB15ZU5eD864gwCo
"""
def pregran(*args):
  import random
  var=args[0]  
  opts=args[0]
  prer = random.choice(["¿Cómo estás" , "¿Que paso" , "¿Que cuentas" , "¿Como te encuentras", "¿Todo bien", "¿Qué tal" , "¿Que hay de nuevo", "¿Que me cuentas", "¿Que me dices" ,"¿Cómo amaneciste", "¿Que has hecho" , "¿Como te va" , "¿Como nos va" , "¿Que me contas" , "¿Ya has comído", "¿Que has soñado"])
  prrhy = random.choice(["¿Cómo estuviste", "¿Que paso", "¿Que cuentas de", "¿Todo bien", "¿Qué tal" , "¿Que hubo de nuevo" , "¿Que me cuentas de" , "¿Que me dices de" ,"¿Cómo amaneciste" , "¿Que has hecho" , "¿Como te fue" , "¿Como nos fue" , "¿Que me contas" , "¿Que comiste", "¿Que soñaste"])
  tiemp = random.choice(["el dia de hoy", "hoy", " "])
  tiemp2 = random.choice(["el dia de ayer", "ayer", " "])
  prim = random.choice([(prer, tiemp, "?") , (prrhy, tiemp2, "?")])
  return 'set_slot {0} "{1}"'.format(var,prim)