# -*- coding: utf-8 -*-
"""random_greeting

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uIZoUMFwpULKMsRsNzbo0q81qBhIJ1o5
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Ivan Vladimir Meza Ruiz 2018
# GPL 3.0

import random

def saludos(*args):
  import random 
  var=args[0]  
  opts=args[0]
  parr = (['Hola,', 'Aloh,', 'Hi,', 'Hey'])
  par = random.choice (parr)
  emor = (['Que gusto', 'Que sorpresa' , 'Que Alegría ', 'Que Asombro' , 'Que placer' , 'Que gozo' , 'Que deleite', 'Que felicidad', 'Que milagro'])
  emo = random.choice(emor)
  very = (['volverte a ver','verte de nuevo', 'verte', 'leerte' , 'volverte a leer', 'leerte de nuevo'])
  ver = random.choice(very)
  salur = ([(par , emo), ( par, emo , ver)])  
  salu = random.choice(salur)
  return 'set_slot {0} "{1}"'.format(var,salu)