# -*- coding: utf-8 -*-
"""random_despedidas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15n8uxuSGDANhwJFrTsHT7FJZMzUrnBBm
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Ivan Vladimir Meza Ruiz 2018
# GPL 3.0
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Ivan Vladimir Meza Ruiz 2018
# GPL 3.0

import random

def despedida(*args):
    var=args[0]
    opts=args[1]

    desp1 = random.choice(["Nos vemos" , "Hasta" , "Te veo"]+opts)
    desp2 = random.choice(["más tarde,", "pronto," ,"luego," ,"mañana,", "cuando puedas,"]+opts)
    desp3 = random.choice(["que todo salga bien", "descansa" , "dulces sueños" , "que tenga un buen día" , "que te vaya bien", "chao" , "bye" , "suerte!!" , "cuídate"]+opts)
    desp4 = random.choice(["Descanses" , "Tengas un buen día" , "Te vaya bien" , "Todo te salga bien"]+opts)
    desped =([(desp1, desp2, desp3), (desp3, desp1, desp2), (desp1, desp2, desp3, "espero que" , desp4), (desp3, desp1, desp2 , "espero que" , desp4)]+opts)
    return 'set_slot {0} "{1}"'.format(var,desped)